Generic tunnel
maticnetwork/pos-portal pull request #53
Opened 2020-09-17 10:34 UTC by jdkanani

2020-09-17 10:46 UTC, arthcp requested changes

2020-09-17 10:46 UTC, arthcp commented on contracts/tunnel/MessageTunnel.sol
> +import {ICheckpointManager} from "./root/RootChainManager/ICheckpointManager.sol";
Need to fix the paths

2020-09-17 10:46 UTC, arthcp commented on contracts/tunnel/MockChildTunnel.sol
> +    function receiveMessage(uint256, bytes calldata data) public only(STATE_SYNCER_ROLE) {
Change function name to `onStateReceive`

2020-09-17 10:46 UTC, arthcp commented on contracts/tunnel/MockChildTunnel.sol
> +        }
`syncType` is only present on child side, it can be confusing so lets keep it consistent

2020-09-23 07:21 UTC, arthcp commented on contracts/tunnel/BaseChildTunnel.sol
> +    }
Also lets remove the only role for this function. Basically, this function is called internally and all restriction etc. need not be implemented by base contract. All that can be done by the implementation contract.

2020-09-23 07:21 UTC, arthcp commented on contracts/tunnel/BaseRootTunnel.sol
> +    }
Same comment as above, lets make this internal and have implementation contract determine when it needs to be called

2020-09-23 07:23 UTC, jdkanani commented on contracts/tunnel/BaseChildTunnel.sol
> +    }
Yeah then we need to make sure we convey this to docs.

2020-09-24 06:33 UTC, arthcp approved these changes

2020-09-24 07:43 UTC, merged